;; ============================================================
;; AUTO-GENERATED — DO NOT EDIT
;; Generated by build.icon-generator from src/icons/*.svg
;; ============================================================
(ns renderer.icon.defaults)

(def defaults {})
