(ns renderer.element.hierarchy)

(defonce hierarchy (atom (make-hierarchy)))

(defn derive-element
  [tag parent]
  (swap! hierarchy derive tag parent))

;; REVIEW: Is this type of complexity really needed?
(derive-element ::graphics ::renderable)
(derive-element ::gradient ::renderable)
(derive-element ::descriptive ::renderable)
(derive-element :foreignObject ::graphics)
(derive-element :textPath ::graphics)
(derive-element :tspan ::graphics)
(derive-element :linearGradient ::gradient)
(derive-element :radialGradient ::gradient)
(derive-element :desc ::descriptive)
(derive-element :metadata ::descriptive)
(derive-element :title ::descriptive)

(defmulti render :tag :hierarchy hierarchy)
(defmulti render-to-string :tag :hierarchy hierarchy)
(defmulti render-edit :tag :hierarchy hierarchy)
(defmulti path :tag :hierarchy hierarchy)
(defmulti area :tag :hierarchy hierarchy)
(defmulti centroid :tag :hierarchy hierarchy)
(defmulti snapping-points :tag :hierarchy hierarchy)
(defmulti bbox :tag :hierarchy hierarchy)
(defmulti translate (fn [el _offset] (:tag el)) :hierarchy hierarchy)
(defmulti scale (fn [el _ratio _pivot-point] (:tag el)) :hierarchy hierarchy)
(defmulti edit (fn [el _offset _handle] (:tag el)) :hierarchy hierarchy)
(defmulti properties identity :hierarchy hierarchy)

(defmethod render :default [])
(defmethod render-to-string :default [el] [render el])
(defmethod render-edit :default [])
(defmethod bbox :default [])
(defmethod area :default [])
(defmethod centroid :default [])
(defmethod snapping-points :default [] [])
(defmethod translate :default [el _offset] el)
(defmethod scale :default [el _ratio _pivot-point] el)
(defmethod edit :default [el _offset _handle _e] el)
(defmethod properties :default [])
