(ns renderer.tool.hierarchy)

(defonce hierarchy (atom (make-hierarchy)))

(defn derive-tool
  [tool parent]
  (swap! hierarchy derive tool parent))

(defmulti on-pointer-down (fn [db _e] (:tool db)) :hierarchy hierarchy)
(defmulti on-pointer-up (fn [db _e] (:tool db)) :hierarchy hierarchy)
(defmulti on-pointer-move (fn [db _e] (:tool db)) :hierarchy hierarchy)
(defmulti on-double-click (fn [db _e] (:tool db)) :hierarchy hierarchy)
(defmulti on-drag-start (fn [db _e] (:tool db)) :hierarchy hierarchy)
(defmulti on-drag (fn [db _e] (:tool db)) :hierarchy hierarchy)
(defmulti on-drag-end (fn [db _e] (:tool db)) :hierarchy hierarchy)
(defmulti on-key-up (fn [db _e] (:tool db)) :hierarchy hierarchy)
(defmulti on-key-down (fn [db _e] (:tool db)) :hierarchy hierarchy)
(defmulti on-activate :tool :hierarchy hierarchy)
(defmulti on-deactivate :tool :hierarchy hierarchy)
(defmulti snapping-points (fn [db _e] (:tool db)) :hierarchy hierarchy)
(defmulti snapping-elements (fn [db _e] (:tool db)) :hierarchy hierarchy)
(defmulti render identity :hierarchy hierarchy)
(defmulti properties identity :hierarchy hierarchy)
(defmulti help (fn [tool state] [tool state]) :hierarchy hierarchy)

(defmulti right-panel identity :hierarchy hierarchy)

(defmethod on-pointer-down :default [db _e] db)
(defmethod on-pointer-up :default [db _e] db)
(defmethod on-pointer-move :default [db _e] db)
(defmethod on-double-click :default [db _e] db)
(defmethod on-drag-start :default [db _e] db)
(defmethod on-drag :default [db _e] db)
(defmethod on-drag-end :default [db _e] db)
(defmethod on-key-up :default [db _e] db)
(defmethod on-key-down :default [db _e] db)
(defmethod on-activate :default [db] db)
(defmethod on-deactivate :default [db] db)
(defmethod render :default [])
(defmethod properties :default [])
(defmethod snapping-points :default [])
(defmethod snapping-elements :default [])
(defmethod help :default [_tool _state] "")
