(ns renderer.tool.hierarchy
  (:require
   [renderer.hierarchy :as hierarchy]))

(defn dispatch [db & _more] [(:tool db) (:state db)])

(defmulti on-pointer-down dispatch :hierarchy hierarchy/hierarchy)
(defmulti on-pointer-up dispatch :hierarchy hierarchy/hierarchy)
(defmulti on-pointer-move dispatch :hierarchy hierarchy/hierarchy)
(defmulti on-double-click dispatch :hierarchy hierarchy/hierarchy)
(defmulti on-drag-start dispatch :hierarchy hierarchy/hierarchy)
(defmulti on-context-menu dispatch :hierarchy hierarchy/hierarchy)
(defmulti on-drag dispatch :hierarchy hierarchy/hierarchy)
(defmulti on-drag-end dispatch :hierarchy hierarchy/hierarchy)
(defmulti on-key-up dispatch :hierarchy hierarchy/hierarchy)
(defmulti on-key-down dispatch :hierarchy hierarchy/hierarchy)
(defmulti snapping-points dispatch :hierarchy hierarchy/hierarchy)
(defmulti snapping-elements dispatch :hierarchy hierarchy/hierarchy)
(defmulti on-delete dispatch :hierarchy hierarchy/hierarchy)
(defmulti help (fn [tool state] [tool state]) :hierarchy hierarchy/hierarchy)
(defmulti render identity :hierarchy hierarchy/hierarchy)
(defmulti attributes-panel identity :hierarchy hierarchy/hierarchy)
(defmulti on-deactivate :tool :hierarchy hierarchy/hierarchy)
(defmulti on-activate (fn [db & {:as _props}] (:tool db))
  :hierarchy hierarchy/hierarchy)

(defmethod on-pointer-down :default [db _e] db)
(defmethod on-pointer-up :default [db _e] db)
(defmethod on-pointer-move :default [db _e] db)
(defmethod on-double-click :default [db _e] db)
(defmethod on-drag-start :default [db _e] db)
(defmethod on-drag :default [db _e] db)
(defmethod on-drag-end :default [db _e] db)
(defmethod on-context-menu :default [db _e] db)
(defmethod on-key-up :default [db _e] db)
(defmethod on-key-down :default [db _e] db)
(defmethod on-activate :default [db & {:as _props}] db)
(defmethod on-deactivate :default [db] db)
(defmethod on-delete :default [db] db)
(defmethod render :default [])
(defmethod snapping-points :default [])
(defmethod snapping-elements :default [])
(defmethod help :default [_tool _state] "")
