name: Outdated dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  antq:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: liquidz/antq-action@main
        with:
          excludes: 'org.clojure/tools.deps.alpha lambdaisland/deep-diff2'
