name: Mirroring

on: [push, delete]

jobs:
  to_codeberg:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v6
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@master
          with:
            REMOTE: 'ssh://git@codeberg.org/repath-studio/repath-studio.git'
            GIT_SSH_PRIVATE_KEY: ${{ secrets.CODEBERG_SSH_PRIVATE_KEY }}
            GIT_SSH_NO_VERIFY_HOST: "true"
